### ISSUE TITLE
Different outputs between Chrome and Firefox

### ISSUE THREAD

**Issue by kelsey-taylor** [stamen/mapbox-gl-style-diff#13]
## Describe the issue

I'm using the differ to investigate changes made in this PR (https://github.com/stamen/amazon-MapStyleSandbox/pull/468), but am seeing different results between Chrome and Firefox. Firefox is showing the results I expect, whereas it seems like Chrome is using an outdated version of the stylesheet from `main` (despite the URL showing the correct path).

Differ URL: https://stamen-styles.s3.us-west-2.amazonaws.com/dist/master/stamen-diff.html?#lstyle=https://stamen-styles.s3.us-west-2.amazonaws.com/dist/main/variants/gaia_en/style.json&rstyle=https://stamen-styles.s3.us-west-2.amazonaws.com/dist/align-zooms/variants/gaia_en/style.json

output in Chrome (unexpected):

<img width="584" alt="Screen Shot 2022-03-07 at 4 25 25 PM" src="https://user-images.githubusercontent.com/57634568/157120370-f8dba8b7-8444-4f43-8de2-a2ebe776a921.png">

output in Firefox (expected):

<img width="507" alt="Screen Shot 2022-03-07 at 4 25 34 PM" src="https://user-images.githubusercontent.com/57634568/157120387-a78b65cb-49fb-4797-810a-a4ba0739b4e0.png">

## Additional context

I'm seeing something similar in the viewer between Chrome and Firefox - could there be caching in one browser that is not reflected in another?

**Comment by ebrelsford** [comment]
Closing this here since the viewer is in a different repo now.
