### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by aparlato** [stamen/mapbox-gl-style-diff#6]
Per [this comment](https://github.com/stamen/mapbox-gl-style-diff/pull/5#issuecomment-1008948503), I think this repo would benefit from unit tests. Since the diffing is intended as a QA step, we want to make sure a break in the code doesn't result in not showing important differences to the user.

@peterqliu what do you think of breaking down `diff.js` into different files (or at least different exported functions) (eg [diffLayerPropertyChanges](https://github.com/stamen/mapbox-gl-style-diff/blob/0bd35f5e4229705be559b998a943d7097509c30f/diff.js#L199-L221)) and testing each individually with test cases that have the known changes we want to diff for?

I suggest using Jest over in https://github.com/stamen/amazon-MapStyleSandbox/issues/320 since I'm familiar with it, but open to whatever.

**Comment by mulloverit** [comment]
Stale! Will open a new ticket if/when needed.
