### ISSUE TITLE
Detect and distinguish changes that have no visual result

### ISSUE THREAD

**Issue by peterqliu** [stamen/mapbox-gl-style-diff#7]
Per shareshare, @almccon mentioned that some style changes (e.g. applying or undoing a default style value) don't result in a visual change, and we can flag that. 

This is doable for most properties, by comparing values against a list of defaults in the style spec. As a first iteration we can just compare literal values, though expressions can also evaluate to equivalent values.

**Comment by mulloverit** [comment]
Stale and unactionable. Closing!
